name: Build Go executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v -ldflags="-s -w" ./...

    - name: Create zip of build Go executable
      uses: actions/upload-artifact@v4
      with:
          name: lyrics-bot
          path: |
            midnight-lyrics-bot
            albums/*
            fonts/*
            images/*
            LICENSE
            README.md
